const INSTRUCTOR = {
  nombre: "Jimmy Marcelo",
  bio: "Profesor de matemáticas y química con más de 10 años preparando preuniversitarios para UNALM, UNMSM, UNA y Villarreal.",
  canal_youtube: "5.44K suscriptores · 196 videos",
};

const CURSOS = [
  {
    id: "analisis-mat-1",
    titulo: "Análisis Matemático I — Ciclo 2026",
    titulo_corto: "Análisis Matemático I",
    universidad: "UNALM",
    descripcion:
      "Curso completo de Análisis Matemático I. Capítulo I: Números reales, inecuaciones, valor absoluto. 55 clases en HD.",
    clases: 55,
    horas: 92,
    precio: 89,
    precio_antes: 149,
    nivel: "Básico-Intermedio",
    color_thumb: "from-orange-400 to-yellow-400",
    preview_titulo: "Clase 1 · Números reales",
    preview_duracion: "2h 08min",
    rating: 4.9,
    resenas: 184,
    alumnos: "1,240",
    actualizacion: "Mar 2026",
    capitulos: [
      { titulo: "Capítulo I: Números reales", clases: 12 },
      { titulo: "Capítulo II: Inecuaciones", clases: 14 },
      { titulo: "Capítulo III: Valor absoluto", clases: 9 },
      { titulo: "Capítulo IV: Funciones", clases: 20 },
    ],
    aprenderas: [
      "Dominar el sistema de los números reales y sus propiedades",
      "Resolver inecuaciones lineales, cuadráticas y polinómicas",
      "Aplicar el concepto de valor absoluto en ecuaciones e inecuaciones",
      "Graficar y analizar funciones reales de variable real",
      "Identificar dominio, rango y composición de funciones",
      "Resolver problemas tipo examen de admisión UNALM",
      "Aplicar teoremas y axiomas de los números reales",
      "Construir gráficas con transformaciones (traslación, reflexión)",
    ],
  },
  {
    id: "analisis-mat-2",
    titulo: "Análisis Matemático II — Ciclo 2026",
    titulo_corto: "Análisis Matemático II",
    universidad: "UNALM",
    descripcion: "Aplicaciones de la derivada, integrales, ecuaciones paramétricas y más. 66 clases.",
    clases: 66,
    horas: 110,
    precio: 99,
    precio_antes: 159,
    nivel: "Intermedio",
    color_thumb: "from-green-400 to-emerald-500",
    preview_titulo: "Clase 1 · Límites y continuidad",
    preview_duracion: "1h 52min",
    rating: 4.8,
    resenas: 96,
    alumnos: "720",
    actualizacion: "Abr 2026",
    capitulos: [
      { titulo: "Capítulo I: Límites y continuidad", clases: 14 },
      { titulo: "Capítulo II: Aplicaciones de la derivada", clases: 16 },
      { titulo: "Capítulo III: Integrales", clases: 20 },
      { titulo: "Capítulo IV: Ecuaciones paramétricas", clases: 16 },
    ],
    aprenderas: [
      "Calcular límites y analizar continuidad de funciones",
      "Aplicar el cálculo diferencial a problemas de optimización",
      "Resolver integrales definidas e indefinidas",
      "Modelar problemas reales con ecuaciones paramétricas",
      "Aplicar el teorema fundamental del cálculo",
      "Calcular áreas y volúmenes con integrales",
      "Trabajar con coordenadas polares",
      "Resolver problemas tipo examen UNALM",
    ],
  },
  {
    id: "quimica-general",
    titulo: "Química General — UNALM",
    titulo_corto: "Química General",
    universidad: "UNALM",
    descripcion:
      "Estequiometría, soluciones, equilibrio químico. Todo lo que necesitas para aprobar Química General.",
    clases: 35,
    horas: 58,
    precio: 69,
    precio_antes: 119,
    nivel: "Básico",
    color_thumb: "from-orange-500 to-red-500",
    preview_titulo: "Clase 1 · Estequiometría básica",
    preview_duracion: "1h 30min",
    rating: 4.7,
    resenas: 72,
    alumnos: "560",
    actualizacion: "Feb 2026",
    capitulos: [
      { titulo: "Capítulo I: Estequiometría", clases: 10 },
      { titulo: "Capítulo II: Soluciones y concentraciones", clases: 9 },
      { titulo: "Capítulo III: Equilibrio químico", clases: 8 },
      { titulo: "Capítulo IV: Ácidos y bases", clases: 8 },
    ],
    aprenderas: [
      "Balancear ecuaciones químicas",
      "Calcular masas molares y conversiones mol-gramo",
      "Resolver problemas de estequiometría",
      "Preparar soluciones con diferentes unidades de concentración",
      "Aplicar el principio de Le Chatelier al equilibrio químico",
      "Calcular pH y pOH de soluciones",
      "Identificar reacciones ácido-base",
      "Resolver problemas tipo examen UNALM",
    ],
  },
  {
    id: "algebra-cepre-unalm",
    titulo: "Álgebra Cepre UNALM",
    titulo_corto: "Álgebra Cepre UNALM",
    universidad: "UNALM",
    descripcion:
      "Curso completo de álgebra para postulantes al CEPRE UNALM. 20 sesiones con ejercicios resueltos.",
    clases: 20,
    horas: 30,
    precio: 59,
    precio_antes: 99,
    nivel: "Básico",
    color_thumb: "from-yellow-400 to-orange-400",
    preview_titulo: "Clase 1 · Expresiones algebraicas",
    preview_duracion: "1h 15min",
    rating: 4.8,
    resenas: 58,
    alumnos: "420",
    actualizacion: "Mar 2026",
    capitulos: [
      { titulo: "Capítulo I: Expresiones algebraicas", clases: 5 },
      { titulo: "Capítulo II: Productos y cocientes notables", clases: 5 },
      { titulo: "Capítulo III: Factorización", clases: 5 },
      { titulo: "Capítulo IV: Ecuaciones e inecuaciones", clases: 5 },
    ],
    aprenderas: [
      "Operar con polinomios y expresiones algebraicas",
      "Aplicar productos y cocientes notables",
      "Factorizar polinomios con distintos métodos",
      "Resolver ecuaciones de primer y segundo grado",
      "Resolver inecuaciones polinómicas",
      "Aplicar el teorema del resto y del factor",
      "Trabajar con divisibilidad algebraica",
      "Resolver problemas tipo examen CEPRE UNALM",
    ],
  },
  {
    id: "clinicas-algebra-villarreal",
    titulo: "Clínicas de Álgebra — Villarreal",
    titulo_corto: "Clínicas de Álgebra",
    universidad: "UNFV",
    descripcion:
      "Clínicas de álgebra enfocadas en el examen de admisión de Villarreal. Cocientes notables, divisibilidad y más.",
    clases: 16,
    horas: 24,
    precio: 49,
    precio_antes: 89,
    nivel: "Básico",
    color_thumb: "from-red-500 to-pink-500",
    preview_titulo: "Clase 1 · Cocientes notables",
    preview_duracion: "1h 00min",
    rating: 4.7,
    resenas: 40,
    alumnos: "310",
    actualizacion: "Feb 2026",
    capitulos: [
      { titulo: "Capítulo I: Cocientes notables", clases: 4 },
      { titulo: "Capítulo II: Divisibilidad algebraica", clases: 4 },
      { titulo: "Capítulo III: Factorización", clases: 4 },
      { titulo: "Capítulo IV: Ecuaciones de Villarreal", clases: 4 },
    ],
    aprenderas: [
      "Resolver cocientes notables con todos los casos",
      "Aplicar el teorema del resto en ejercicios complejos",
      "Factorizar con métodos avanzados (aspa simple, doble)",
      "Resolver ecuaciones del estilo Villarreal",
      "Trabajar con divisibilidad de polinomios",
      "Resolver ejercicios de los últimos exámenes de admisión",
      "Aplicar técnicas de simplificación rápida",
      "Maximizar puntaje en el examen UNFV",
    ],
  },
  {
    id: "cepre-una",
    titulo: "Cepre UNA Puno",
    titulo_corto: "Cepre UNA Puno",
    universidad: "UNA",
    descripcion:
      "Preparación enfocada para el examen Cepre de la Universidad Nacional del Altiplano.",
    clases: 8,
    horas: 12,
    precio: 39,
    precio_antes: 79,
    nivel: "Básico",
    color_thumb: "from-blue-400 to-indigo-500",
    preview_titulo: "Clase 1 · Aritmética básica",
    preview_duracion: "0h 55min",
    rating: 4.6,
    resenas: 22,
    alumnos: "180",
    actualizacion: "Ene 2026",
    capitulos: [
      { titulo: "Capítulo I: Aritmética", clases: 2 },
      { titulo: "Capítulo II: Álgebra básica", clases: 2 },
      { titulo: "Capítulo III: Geometría", clases: 2 },
      { titulo: "Capítulo IV: Trigonometría", clases: 2 },
    ],
    aprenderas: [
      "Dominar operaciones básicas de aritmética",
      "Resolver razones, proporciones y porcentajes",
      "Aplicar álgebra básica a problemas Cepre",
      "Calcular áreas y perímetros de figuras planas",
      "Resolver triángulos rectángulos",
      "Aplicar identidades trigonométricas fundamentales",
      "Resolver problemas tipo examen UNA",
      "Manejar técnicas de resolución rápida",
    ],
  },
];

const TESTIMONIOS = [
  {
    nombre: "Carlos M.",
    universidad: "Ingresó a UNALM 2025-II",
    texto:
      "Las clases del profe Jimmy son las mejores. Entendí inecuaciones que no había logrado en 2 años de academia.",
  },
  {
    nombre: "Andrea L.",
    universidad: "Ingresó a UNMSM 2025-I",
    texto:
      "Compré el de Análisis Mat I y aprobé el examen. El temario está perfectamente ordenado.",
  },
  {
    nombre: "Diego R.",
    universidad: "Cachimbo UNALM",
    texto:
      "Mucho mejor que ir a una academia presencial. Veo las clases las veces que quiero.",
  },
];

const REVIEWS = [
  { nombre: "Renato P.", fecha: "hace 2 semanas", estrellas: 5, texto: "Excelente, el profe explica cada paso. Las inecuaciones nunca habían sido tan claras." },
  { nombre: "María G.", fecha: "hace 1 mes", estrellas: 5, texto: "El temario está ordenado y los PDFs ayudan muchísimo a repasar." },
  { nombre: "Luis A.", fecha: "hace 1 mes", estrellas: 4, texto: "Muy buen curso. Me hubiera gustado algunos ejercicios extra de funciones." },
  { nombre: "Camila S.", fecha: "hace 2 meses", estrellas: 5, texto: "Jimmy responde rápido en el chat. Vale cada sol." },
  { nombre: "Fernando R.", fecha: "hace 3 meses", estrellas: 5, texto: "Pasé el examen de admisión gracias a este curso. Gracias profe!" },
];

const APRENDERAS = [
  "Dominar el sistema de los números reales y sus propiedades",
  "Resolver inecuaciones lineales, cuadráticas y polinómicas",
  "Aplicar el concepto de valor absoluto en ecuaciones e inecuaciones",
  "Graficar y analizar funciones reales de variable real",
  "Identificar dominio, rango y composición de funciones",
  "Resolver problemas tipo examen de admisión UNALM",
  "Aplicar teoremas y axiomas de los números reales",
  "Construir gráficas con transformaciones (traslación, reflexión)",
];

// Estado dinámico del canal — en producción esto vendrá de la API de YouTube Live / backend
const EN_VIVO = false; // poné en true para ver el estado "clase en vivo"

const PROXIMA_LIVE = {
  fecha: "Martes 21 de mayo",
  hora: "19:00",
  titulo: "Resolución de inecuaciones — Cap I",
  curso: "Análisis Matemático I",
};

const ULTIMO_VIDEO = {
  titulo: "Clase 55. Análisis Matemático I",
  capitulo: "Capítulo I: Números reales",
  duracion: "5h 43min",
  publicado: "hace 3 semanas",
  vistas: "181",
  color_thumb: "from-orange-400 to-yellow-400",
  url: "https://www.youtube.com/@arsmagnaconjimmymarcelo/videos", // reemplazar por URL específica del video cuando se conozca
};

Object.assign(window, {
  INSTRUCTOR,
  CURSOS,
  TESTIMONIOS,
  REVIEWS,
  APRENDERAS,
  EN_VIVO,
  PROXIMA_LIVE,
  ULTIMO_VIDEO,
});
